### PR TITLE
Add JNGL

### PR DESCRIPTION
**Pull request by pinguin999**

### CODE REVIEW

**Review by pinguin999 — COMMENTED** [review]
Add JNGL

**Comment by stevinz** [comment]
Thanks for contributing, looks like a great game library.

I would like to add it to this repo, however, I don't feel like JNGL should be in the 'Specialty' category. The main 'Game Engine' category in general is usually reserved for commercial game engines that have full game design capabilities (editor, scripting, publishing, etc). And the sub category 'Specialty' was added for game engines that don't produce typical games or design games in an unusual way. I have thought about removing that category all together...

With that said, JNGL looks like a great fit for the [C++ Game Frameworks](https://github.com/stevinz/awesome-game-engine-dev#c-game-framework-1) category. It looks akin to [LOVE](https://love2d.org/) or [Solar / Corona](https://solar2d.com/).

**Comment by pinguin999** [comment]
Thanks for explaining. I have moved JNGL to C++ Frameworks.

**Comment by stevinz** [comment]
Looks good, thanks!

**Pull request merged**
